### ISSUE TITLE
Broken link on front page: http://www.consumerfinance.gov/developers/sourcecodepolicy/

### ISSUE THREAD

**Issue by david-a-wheeler** [cfpb/source-code-policy#2]
This link on the front page is broken:
http://www.consumerfinance.gov/developers/sourcecodepolicy/

**Comment by Scotchester** [comment]
Eek! Unintended consequence of redirecting http://www.consumerfinance.gov/developers to http://cfpb.github.io/

Thanks for letting us know! We'll get it fixed.

**Comment by virtix** [comment]
:bug:

**Comment by Scotchester** [comment]
That PR didn't actually fix this issue, because the repo name has dashes in it, but the front page link has none. This is something we need to fix with our redirect. Reopening.

**Comment by Scotchester** [comment]
Check that, I don't have privileges to do so. @virtix, if you please?

**Comment by rosskarchner** [comment]
We're back on the air!

**Comment by saracope** [comment]
I just noticed this link is broken again.

**Comment by Scotchester** [comment]
@rosskarchner, can you help troubleshoot this?

I suspect that you simply have a generic redirect for
http://www.consumerfinance.gov/developers/* -> http://cfpb.github.io/*

So when someone tries http://www.consumerfinance.gov/developers/sourcecodepolicy/, they're getting sent to http://cfpb.github.io/sourcecodepolicy/

But this repo has dashes in the name, so we need a specific rule for
www.consumerfinance.gov/developers/sourcecodepolicy/ -> https://cfpb.github.io/source-code-policy/

**Comment by rosskarchner** [comment]
hm-- the "old" fix was simply to not redirect /developers/sourcecodepolicy/ (letting the CMS page shine through). I'm not sure what stomped on that.

So is redirecting to github.io what we actually want right now?

**Comment by Scotchester** [comment]
Yes, please.

**Comment by rosskarchner** [comment]
done

**Comment by Scotchester** [comment]
Will it take some amount of time to propagate?

**Comment by rosskarchner** [comment]
it shouldn't-- I don't think Akamai caches redirects. I'll kick it just in case, though

**Comment by Scotchester** [comment]
It's still trying to go to http://cfpb.github.io/sourcecodepolicy/ (with no dashes).

**Comment by rosskarchner** [comment]
Maybe there's something cached in your browser?

I've seen this work on multiple machines, multiple browsers: www.consumerfinance.gov/developers/sourcecodepolicy/

**Comment by rosskarchner** [comment]
Another way to test it:

http://onlinecurl.com/

**Comment by Scotchester** [comment]
Weird... it does seem to be a browser cache issue of some kind. The other browsers I have available are indeed redirecting correctly now. Alrighty, closing this down!
